//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle_Livraria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Livro
    {
        public int IdLivro { get; set; }
        [Display(Name = "Título do Livro")]
        [Required(ErrorMessage = "Informe o título do livro", AllowEmptyStrings = false)]
        public string NomeLivro { get; set; }
        [Display(Name = "Autor(es) do Livro")]
        [Required(ErrorMessage = "Informe o(s) autor(es) do livro", AllowEmptyStrings = false)]
        public string AutorLivro { get; set; }
        [Display(Name = "Número de Páginas")]
        [Required(ErrorMessage = "Informe o número de páginas do livro", AllowEmptyStrings = false)]
        public int PaginasLivro { get; set; }
        [Display(Name = "Editora")]
        [Required(ErrorMessage = "Informe a editora", AllowEmptyStrings = false)]
        public string EditoraLivro { get; set; }
    }
}
